name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Установка Docker и Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Сборка и запуск контейнеров
      - name: Build and start services
        run: |
          docker-compose up --build -d

      # Ждём, пока сервисы запустятся
      - name: Wait for services
        run: |
          sleep 15

      # Запуск unit-тестов
      - name: Run tests for quiz-service
        run: |
          docker exec test-system-quiz-service-1 python manage.py test

      - name: Run tests for user-service
        run: |
          docker exec test-system-user-service-1 python manage.py test

      # Остановка контейнеров
      - name: Tear down
        if: always()
        run: |
          docker-compose down